[package]
name = "busyboredom"
version = "0.1.0"
authors = ["Charlie Wilkin <cwilkin@protonmail.com>"]
edition = "2018"

[dependencies]
actix-rt = "1"
actix-web = "3"
actix-files = "0"
actix-session = "0"
rust-embed = "5"
mime_guess = "2"
futures = "0"
env_logger = "0"
cached = "0"
serde = "1"
log = "0"
captcha = "0"
rand = "0"
lru = "0"

[dependencies.lettre]
version = "0.10.0-alpha.4"
default-features = false
features = ["smtp-transport", "builder", "rustls-tls"]

[build-dependencies]
walkdir = "2.3.1"
regex = "1"
sha-1 = "0"
blake3 = "0"
base64 = "0"

[profile.release]
lto = true