[package]
name = "busyboredom"
version = "0.1.0"
authors = ["Charlie Wilkin <cwilkin@protonmail.com>"]
edition = "2018"

[dependencies]
actix = "0.12"
actix-web = "4.0.0-beta.21"
actix-files = "0.6.0-beta.15"
actix-session = "0.5.0-beta.7"
actix-web-actors = "4.0.0-beta.10"
bytestring = "1"
rust-embed = "6"
mime_guess = "2"
futures = "0"
env_logger = "0"
cached = "0"
log = "0"
captcha = "0"
rand = "0"
lru = "0"
acceptxmr = "0.10"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[dependencies.lettre]
version = "0.10.0-rc.4"
default-features = false
features = ["smtp-transport", "builder", "native-tls"]

[build-dependencies]
walkdir = "2.3"
regex = "1"
sha-1 = "0"
blake3 = "1"
base64 = "0"

[profile.release]
lto = true